(function(){
 const API=window.BYTEFEST_CONFIG.API_URL,token=sessionStorage.getItem("bytefest_bughunt_token"),expected=document.body.dataset.round;
 const PAGE={waiting_start:"bughunt-waiting.html",round1:"bughunt-round1.html",round2:"bughunt-round2.html",round3:"bughunt-round3.html",surprise:"bughunt-surprise.html",final:"bughunt-final.html",awaiting_ranking:"bughunt-waiting.html",eliminated:"bughunt-waiting.html",completed:"bughunt-waiting.html"};
 if(!token){location.replace("participant-login.html");return}
 history.pushState(null,"",location.href);addEventListener("popstate",()=>history.go(1));
 const secureSessionKey="bytefest_bughunt_secure_session",coordinatorGrantKey="bytefest_bughunt_coordinator_grant",mobileDevice=matchMedia("(max-width: 900px), (pointer: coarse)").matches;
 let state=null,secureStarted=sessionStorage.getItem(secureSessionKey)==="1",enforceFullscreenThisPage=false,violationBusy=false,lastViolation=0,clockTimer=null,hiddenStartedAt=null,fullscreenTimer=null,currentQuestion=null;

 async function request(path,opt={}){
  const headers={...(opt.headers||{}),Authorization:`Bearer ${token}`};if(opt.body&&!headers["Content-Type"])headers["Content-Type"]="application/json";
  const r=await fetch(`${API}/api/bughunt${path}`,{...opt,headers}),t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{}
  if(r.status===401){sessionStorage.removeItem("bytefest_bughunt_token");sessionStorage.removeItem(coordinatorGrantKey);location.replace("participant-login.html");throw new Error("Session expired")}
  if(!r.ok){const e=new Error(d.message||`Request failed (${r.status})`);e.status=r.status;e.data=d;throw e}return d;
 }
 function label(k){return({round1:"ROUND 1 · BUG RADAR",round2:"ROUND 2 · PATCH IT",round3:"ROUND 3 · HIDDEN FAILURE",surprise:"SURPRISE BUG DROP",final:"FINAL · CRITICAL DEBUG"})[k]||(k||"").replaceAll("_"," ").toUpperCase()}
 function renderStages(active,count){const box=document.getElementById("stageProgress");box.replaceChildren();for(let i=1;i<=count;i++){const n=document.createElement("span");n.className=`stage ${i<active?"done":i===active?"active":""}`;n.textContent=i<active?`Stage ${i} ✓`:i===active?`Stage ${i} ●`:`Stage ${i} 🔒`;box.appendChild(n)}}
 function clock(end){clearInterval(clockTimer);const el=document.getElementById("clockPill");if(!end){el.textContent="TIME --:--";return}const tick=()=>{const ms=Math.max(0,new Date(end).getTime()-Date.now()),s=Math.floor(ms/1000);el.textContent=`TIME ${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;if(ms<=0)setTimeout(route,900)};tick();clockTimer=setInterval(tick,1000)}
 function showState(d){state=d;document.getElementById("teamLabel").textContent=d.registrationId;document.getElementById("roundLabel").textContent=label(d.currentRound);document.getElementById("scoreValue").textContent=d.qualificationScore;document.getElementById("violationPill").textContent=`SECURITY ${d.security.violations}/${d.security.maxViolations}`;renderStages(d.currentStage,d.stageCount);clock(d.phaseEndsAt);if(d.security.locked)showLock(d)}
 function renderHints(list){const box=document.getElementById("hintList");box.replaceChildren();if(!list||!list.length){const e=document.createElement("div");e.className="hint-card";e.textContent="No hint for this challenge.";box.appendChild(e);return}(list||[]).forEach(h=>{const card=document.createElement("div");card.className="hint-card";const b=document.createElement("button");b.type="button";b.innerHTML=`<span>${h.used?`View Hint Again`:`Use Hint`}</span><span>${h.used?"USED":`-${h.penalty}`}</span>`;const txt=document.createElement("div");txt.className="hint-text";if(h.used){txt.textContent=h.text;card.classList.add("open")}b.onclick=async()=>{if(h.used){card.classList.toggle("open");return}try{const d=await request(`/hint/${h.number}`,{method:"POST"});txt.textContent=d.text;h.text=d.text;h.used=true;card.classList.add("open");b.innerHTML=`<span>View Hint Again</span><span>USED</span>`;await loadState(false)}catch(e){setStatus(e.message,true)}};card.append(b,txt);box.appendChild(card)})}
 function setStatus(m,bad=false){const el=document.getElementById("answerStatus");el.textContent=m||"";el.className=`status ${bad?"bad":"good"}`}
 function renderHidden(passed,total,accepted=false){const box=document.getElementById("hiddenTests");box.hidden=false;let html='<div class="hidden-title">HIDDEN TEST STATUS</div><div class="hidden-grid">';for(let i=1;i<=total;i++)html+=`<div class="hidden-case ${i<=passed?'pass':'fail'}">Test ${i} ${i<=passed?'✓':'✕'}</div>`;html+='</div><small>Exact hidden test data stays private.</small>';if(accepted)html+='<div class="accepted-badge">PATCH ACCEPTED</div>';box.innerHTML=html}
 async function loadQuestion(){try{const d=await request("/question");currentQuestion=d.question;document.getElementById("stageTitle").textContent=d.question.title;document.getElementById("questionPrompt").textContent=d.question.prompt;const editor=document.getElementById("patchEditor");if(window.BytefestQuestionUI){window.BytefestQuestionUI.render(d.question,{mount:document.querySelector(".question-box"),editor})}renderHints(d.question.hints);document.getElementById("runPanel").hidden=true;document.getElementById("hiddenTests").hidden=true;clock(d.phaseEndsAt);document.getElementById("submitAnswerButton").disabled=false;document.getElementById("runCodeButton").disabled=false;setStatus("")}catch(e){if(e.status===423){await loadState(false);return}setStatus(e.message,e.status!==409);document.getElementById("submitAnswerButton").disabled=e.status===409}}
 async function loadState(check=true){const d=await request("/state");showState(d);if(check&&d.currentRound!==expected)location.replace(PAGE[d.currentRound]||"bughunt-waiting.html");return d}
 async function route(){const d=await request("/state");location.replace(PAGE[d.currentRound]||"bughunt-waiting.html")}

 document.getElementById("resetPatchButton").onclick=()=>{const e=document.getElementById("patchEditor");e.value=e.dataset.original||"";document.getElementById("runPanel").hidden=true;setStatus("Patch reset.")};
 document.getElementById("runCodeButton").onclick=async()=>{const b=document.getElementById("runCodeButton"),patch=document.getElementById("patchEditor").value;b.disabled=true;setStatus("Running sample...");try{const d=await request("/run",{method:"POST",body:JSON.stringify({patch})});document.getElementById("runPanel").hidden=false;document.getElementById("runOutput").textContent=d.output||"(no output)";document.getElementById("runNote").textContent=d.note||"";setStatus("Sample run completed.")}catch(e){setStatus(e.message,true)}finally{b.disabled=false}};
 document.getElementById("answerForm").onsubmit=async e=>{e.preventDefault();const b=document.getElementById("submitAnswerButton"),patch=document.getElementById("patchEditor").value;b.disabled=true;setStatus("Checking hidden tests...");try{const d=await request("/submit",{method:"POST",body:JSON.stringify({patch,round:expected})});renderHidden(Number(d.passed||0),Number(d.total||4),Boolean(d.correct));if(!d.correct){setStatus(d.message,true);b.disabled=false;return}setStatus(d.message);await loadState(false);if(!d.completedRound){setTimeout(loadQuestion,900);b.disabled=false}else{document.getElementById("questionPrompt").textContent=d.currentRound==="awaiting_ranking"?"Surprise completed. Waiting for the remaining active teams before qualification ranking.":"Round completed. Moving to your next level...";setTimeout(route,1100)}}catch(err){setStatus(err.message,true);b.disabled=false}};

 function beep(freq=880,duration=.35,gain=.12){try{const C=AudioContext||webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=freq;g.gain.value=gain;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+duration)}catch{}}
 function showLock(d){beep(920,.45,.14);const grant=sessionStorage.getItem(coordinatorGrantKey)||"";const input=document.getElementById("coordinatorAccessKey"),note=document.getElementById("coordinatorSessionNote"),maxed=d.security.violations>=d.security.maxViolations;document.getElementById("lockCount").textContent=`${d.security.violations}/${d.security.maxViolations}`;document.getElementById("lockReason").textContent=d.security.lockReason||"Security violation";document.getElementById("disqualifyButton").hidden=!maxed;if(grant&&!maxed){input.value="";input.hidden=true;input.required=false;if(note){note.textContent="Coordinator already verified on this device. Press RESUME.";note.className="coordinator-session-note good"}}else{input.hidden=false;input.required=!grant;if(note){note.textContent=grant&&maxed?"Coordinator session active. RESUME needs no password; DISQUALIFY needs the coordinator key.":"Coordinator verification is required once on this device.";note.className=`coordinator-session-note ${grant?"good":""}`}}document.getElementById("securityLock").classList.add("active")}
 async function violation(reason,detail=""){if(!secureStarted||violationBusy||state?.security?.locked)return;const now=Date.now();if(now-lastViolation<1500)return;lastViolation=now;violationBusy=true;beep(980,.22,.11);try{await request("/security/violation",{method:"POST",body:JSON.stringify({reason,detail})});await loadState(false);showLock(state)}catch{}finally{violationBusy=false}}

 // Anti-cheat: direct interaction violations.
 document.addEventListener("copy",e=>{if(!secureStarted)return;e.preventDefault();violation("Copy attempt","Copy from competition page was blocked")});
 document.addEventListener("paste",e=>{if(!secureStarted)return;e.preventDefault();violation("Paste attempt","Paste into competition page was blocked")});
 document.addEventListener("cut",e=>{if(!secureStarted)return;e.preventDefault();violation("Cut attempt","Cut from competition page was blocked")});
 document.addEventListener("contextmenu",e=>{if(!secureStarted)return;e.preventDefault();violation("Right-click attempt","Context menu was blocked")});
 document.addEventListener("drop",e=>{if(!secureStarted)return;e.preventDefault();violation("Drag/drop attempt","Drag/drop text or files was blocked")});
 document.addEventListener("keydown",e=>{if(!secureStarted)return;const k=String(e.key||"").toLowerCase();const dev=(e.key==="F12")||(e.ctrlKey&&e.shiftKey&&["i","j","c"].includes(k))||(e.ctrlKey&&k==="u");const clip=(e.ctrlKey||e.metaKey)&&["c","v","x"].includes(k);if(dev||clip){e.preventDefault();violation(dev?"Developer tools shortcut attempt":"Clipboard shortcut attempt",`${e.ctrlKey?'Ctrl+':''}${e.shiftKey?'Shift+':''}${e.key}`)}});

 // Smart focus detection: ignore browser password/notification popups because blur alone is never a violation.
 // A hidden page must stay hidden >3s. Very long gaps (>60s) are treated as device sleep/timeout and ignored.
 document.addEventListener("visibilitychange",()=>{
   if(!secureStarted)return;
   if(document.hidden){hiddenStartedAt=Date.now();return}
   if(hiddenStartedAt){const duration=Date.now()-hiddenStartedAt;hiddenStartedAt=null;if(duration>=3000&&duration<=60000)violation("Tab / app switch",`Competition page hidden for ${(duration/1000).toFixed(1)} seconds`)}
 });
 document.addEventListener("fullscreenchange",()=>{clearTimeout(fullscreenTimer);if(secureStarted&&enforceFullscreenThisPage&&!document.fullscreenElement&&!state?.security?.locked){fullscreenTimer=setTimeout(()=>{if(!document.fullscreenElement&&!document.hidden)violation("Fullscreen exited","Desktop secure mode left fullscreen")},1800)}});

 async function startSecure(){if(!mobileDevice&&!secureStarted){await document.documentElement.requestFullscreen();enforceFullscreenThisPage=true}secureStarted=true;sessionStorage.setItem(secureSessionKey,"1");document.getElementById("secureGate").classList.remove("active");await loadState(false);await loadQuestion()}
 document.getElementById("enterSecureButton").onclick=async()=>{try{await startSecure()}catch{document.getElementById("secureStatus").textContent=mobileDevice?"Tap START SECURE MODE again.":"Fullscreen permission is required for desktop secure mode."}};
 document.getElementById("unlockForm").onsubmit=async e=>{e.preventDefault();try{const d=await request("/security/unlock",{method:"POST",body:JSON.stringify({password:document.getElementById("coordinatorAccessKey").value,grant:sessionStorage.getItem(coordinatorGrantKey)||"",action:"resume"})});if(d.unlockGrant)sessionStorage.setItem(coordinatorGrantKey,d.unlockGrant);document.getElementById("securityLock").classList.remove("active");document.getElementById("coordinatorAccessKey").value="";document.getElementById("unlockStatus").textContent="";if(!mobileDevice&&document.fullscreenEnabled){await document.documentElement.requestFullscreen().then(()=>{enforceFullscreenThisPage=true}).catch(()=>{})}secureStarted=true;sessionStorage.setItem(secureSessionKey,"1");await loadState(false);await loadQuestion()}catch(err){document.getElementById("unlockStatus").textContent=err.message}};
 document.getElementById("disqualifyButton").onclick=async()=>{if(!confirm("Disqualify this team?"))return;try{await request("/security/unlock",{method:"POST",body:JSON.stringify({password:document.getElementById("coordinatorAccessKey").value,grant:sessionStorage.getItem(coordinatorGrantKey)||"",action:"disqualify"})});location.replace("bughunt-waiting.html")}catch(err){document.getElementById("unlockStatus").textContent=err.message}};
 if(secureStarted){document.getElementById("secureGate").classList.remove("active");loadState(false).then(()=>loadQuestion()).catch(()=>{})}else{if(mobileDevice){document.querySelector("#secureGate h2").textContent="Ready on Team Device?";document.querySelector("#secureGate .lead").textContent="Phone/tablet mode does not require fullscreen. Copy/paste and confirmed app switching are monitored.";document.getElementById("enterSecureButton").textContent="START SECURE MODE"}loadState(false).catch(()=>{})}
 setInterval(()=>{if(secureStarted&&!state?.security?.locked)loadState(true).catch(()=>{})},4000);
})();
